wallpaper {
    monitor = HDMI-A-4
    path = /home/thanaphoom/Pictures/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/thanaphoom/Pictures/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/thanaphoom/Pictures/wallpaper.png
    fit_mode = cover
}

splash = false
